title: the bentoBlog
owner: Sabrina Carroll
copyright: voidlingBento
email: dumplings@voidlings.us
tagline: being the copiled ramblings of the void
description: >- # this means to ignore newlines until "baseurl:"
  the BentoBlog is the compiled ramblings of the void, and home to the writings of voidlingBento, the internet’s favorite steamer basket.
  We are queer content creators sharing a body: White Rabbit (aka rabbitDumpling), Black Cat (aka kittyGyoza) and Broken Muse (aka corvidRangoon).
  Enjoy ramblings and essays about our various projects. When not working on them, we are usually found streaming with our very wonderful partners.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.voidlings.us" # the base hostname & protocol for your site, e.g. http://example.com
language: en
twitter_username: voidlingBento
github_username: voidlingBento

images: "https://blog.voidlings.us/assets/images" # live
#images: "http://localhost:4000/assets/images" # test 
permalink: /:year:month/:title/

paginate: 5
paginate_path: /page:num

excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - Gemfile
   - Gemfile.lock

include:
   - .htaccess